name    'AlexCline-disk_stats'
version '0.2.0'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'A Puppet module containing a set of facts about system disk stats and usage.'
description 'A Puppet module containing a set of facts about system disk stats and usage.'
project_page 'https://github.com/AlexCline/disk_stats'
